branch-defaults:
  default:
    environment: null
    group_suffix: null
deploy:
  artifact: ../bundlec1.zip
global:
  application_name: customer1
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
