AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  DynamoDecksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: decks-master
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 50
        WriteCapacityUnits: 50
      SSESpecification:
        SSEEnabled: true

  DynamoGamesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: games-master
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 50
        WriteCapacityUnits: 50
      SSESpecification:
        SSEEnabled: true