AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Test Stuff
    
Globals:
    Function:
        Timeout: 20

Resources:
    RoleForLambdas:
        Type: AWS::IAM::Role
        Properties: 
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement: 
                    Effect: "Allow"
                    Principal: 
                        Service: "lambda.amazonaws.com"
                    Action: "sts:AssumeRole"
            ManagedPolicyArns: 
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
                - arn:aws:iam::aws:policy/service-role/AWSLambdaRole

    PolicyForAuthenticatedUsers:
        Type: AWS::IAM::Policy
        Properties: 
            PolicyName: DoCaaSPolicyForAuthenticatedUsers
            PolicyDocument: 
                Version: "2012-10-17"
                Statement: 
                    - 
                        Effect: "Allow"
                        Action: 
                            - "dynamodb:*"
                        Resource: "*"
                        Condition: 
                            ForAllValues:StringEquals: 
                                dynamodb:LeadingKeys: 
                                    - ”${cognito-identity.amazonaws.com:sub}"
            Roles:
                - "labels-lambda-role2"

    RoleForAuthenticatedCognitoUsers:
        Type: AWS::IAM::Role
        Properties: 
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement: 
                    - 
                        Effect: "Allow"
                        Principal: 
                            Federated: 
                                - "cognito-identity.amazonaws.com"
                        Action: "sts:AssumeRoleWithWebIdentity"
            ManagedPolicyArns: 
                - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

Outputs:
    RoleForLambdas:
        Description: "IAM execution Role for Lambda functions"
        Value: !GetAtt RoleForLambdas.Arn
    PolicyForAuthenticatedUsers:
        Description: "IAM Role for Authenticated Cognito Users"
        Value: !Ref PolicyForAuthenticatedUsers
    RoleForAuthenticatedCognitoUsers:
      Description: "IAM Role for Authenticated Cognito Users"
      Value: !Ref RoleForAuthenticatedCognitoUsers


