AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  DynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: data-customer1
      PrimaryKey:
        Name: partition-key
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 50
        WriteCapacityUnits: 50
      SSESpecification:
        SSEEnabled: true